name: add download buttons to PTCs

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: add missing download buttons
      run: bash ./assets/scripts/add_download.sh
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Add missing download buttons to PTCs
        branch: master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GONSIE }}
