name: update catalog table of contents

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rebuild the catalog index
      run: bash ./assets/scripts/update_toc.sh
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Update catalog index
        branch: master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GONSIE }}
